export const ActionTypes = {
    SET_BLOGS : "SET_BLOGS",
    SELECTED_BLOG : "SELECTED_BLOG",
    REMOVE_SELECTED_BLOG: "REMOVE_SELECTED_BLOG",
    SET_USER: "SET_USER",
    LOGOUT_USER: "LOGOUT_USER"
}